language: java
sudo: false

jdk:
  - oraclejdk8

env:
 - TERM=dumb

script:
 - JAVA_OPTS="-Xmx384m -XX:+UseG1GC" ./gradlew check
 - JAVA_OPTS="-Xmx384m -XX:+UseG1GC" ./gradlew check -Dcache
 - JAVA_OPTS="-Xmx384m -XX:+UseG1GC" ./gradlew check -Dcache -DweakKeys
 - JAVA_OPTS="-Xmx384m -XX:+UseG1GC" ./gradlew check -Dcache -DweakKeys -DweakValues
 - JAVA_OPTS="-Xmx384m -XX:+UseG1GC" ./gradlew check -Dcache -DweakKeys -DsoftValues
 - JAVA_OPTS="-Xmx384m -XX:+UseG1GC" ./gradlew check -Dcache -DsoftValues

after_success:
- ./gradlew jacocoTestReport coveralls
