language: java
sudo: false

jdk:
  - oraclejdk8

env:
 - TERM=dumb

before_install:
 - cp gradle.properties.ci gradle.properties

script:
 - JAVA_OPTS="-Xmx384m -XX:+UseG1GC -XX:SoftRefLRUPolicyMSPerMB=0 -noverify" ./gradlew check
 - sh -c 'cd examples/write-behind-rxjava && mvn test'

after_success:
- ./gradlew coveralls uploadArchives

matrix:
  fast_finish: true

addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
    - $HOME/.gradle
