language: java
sudo: false

jdk:
  - oraclejdk8

env:
 - TERM=dumb

before_install:
 - cp gradle.properties.ci gradle.properties

script:
 - JAVA_OPTS="-Xmx384m -XX:+UseG1GC -XX:SoftRefLRUPolicyMSPerMB=10 -XX:MaxMetaspaceSize=128m -noverify" ./gradlew check

after_success:
- ./gradlew coveralls uploadArchives

matrix:
  fast_finish: true
